tinydocker: src/cgroup/cgroup.c File Reference
cgroup.c File Reference
#include "cgroup.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "../utils/utils.h"
Macros
#define _GNU_SOURCE
#define CGROUP_BASE_PATH "/sys/fs/cgroup"
Functions
CGroup * cgroup_create (const char *name, int max_cpus, long max_memory)
Create a new control group.
int cgroup_add_process (CGroup *cgroup, pid_t pid)
Add a process to a control group.
int cgroup_apply_limits (CGroup *cgroup)
Apply resource limits to a control group.
int cgroup_destroy (CGroup *cgroup)
Destroy a control group.
void cgroup_free (CGroup *cgroup)
Free resources associated with a control group.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file cgroup.c.
CGROUP_BASE_PATH
#define CGROUP_BASE_PATH "/sys/fs/cgroup"
Definition at line 13 of file cgroup.c.
Function Documentation
cgroup_add_process()
int cgroup_add_process (CGroup * cgroup, pid_t pid)
Add a process to a control group.
Adds the specified process to the control group, applying the resource limits.
Parameters
cgroup Pointer to the CGroup structure
pid Process ID to add to the control group
Returns
EXIT_SUCCESS on success, EXIT_FAILURE on failure
Definition at line 67 of file cgroup.c.
References CGroup::path, CGroup::pid, and write_str_to_file().
Referenced by main().
cgroup_apply_limits()
int cgroup_apply_limits (CGroup * cgroup)
Apply resource limits to a control group.
Sets the CPU and memory limits for the control group.
Parameters
cgroup Pointer to the CGroup structure
Returns
EXIT_SUCCESS on success, EXIT_FAILURE on failure
Definition at line 98 of file cgroup.c.
References CGroup::max_cpus, CGroup::max_memory, CGroup::path, and write_str_to_file().
Referenced by main().
cgroup_create()
CGroup* cgroup_create (const char * name, int max_cpus, long max_memory)
Create a new control group.
Creates a new control group with the specified name and resource limits. The control group is created in the cgroup filesystem.
Parameters
name Name of the control group
max_cpus Maximum number of CPUs allowed
max_memory Maximum memory allowed in bytes
Returns
Pointer to the created CGroup structure, or NULL on failure
Definition at line 15 of file cgroup.c.
References CGROUP_BASE_PATH, cgroup_free(), CGroup::max_cpus, CGroup::max_memory, CGroup::name, CGroup::path, and CGroup::pid.
Referenced by main().
cgroup_destroy()
int cgroup_destroy (CGroup * cgroup)
Destroy a control group.
Removes the control group from the filesystem.
Parameters
cgroup Pointer to the CGroup structure
Returns
EXIT_SUCCESS on success, EXIT_FAILURE on failure
Definition at line 160 of file cgroup.c.
References CGroup::path.
Referenced by main().
cgroup_free()
void cgroup_free (CGroup * cgroup)
Free resources associated with a control group.
Frees all memory allocated for the control group structure.
Parameters
cgroup Pointer to the CGroup structure
Definition at line 174 of file cgroup.c.
References CGroup::name, and CGroup::path.
Referenced by cgroup_create(), and main().