tinydocker: src/cli/cli.c File Reference
cli.c File Reference
#include "cli.h"
#include <errno.h>
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../container/container.h"
Macros
#define _GNU_SOURCE
#define DEFAULT_HOSTNAME "container"
#define DEFAULT_ROOTFS "./rootfs"
#define DEFAULT_CPUS 1
#define DEFAULT_MEMORY (512 * 1024 * 1024)
Functions
static void print_usage (const char *program_name)
int parse_args (int argc, char *argv[], ContainerArgs *args)
Parse command-line arguments.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file cli.c.
DEFAULT_CPUS
#define DEFAULT_CPUS 1
Definition at line 14 of file cli.c.
DEFAULT_HOSTNAME
#define DEFAULT_HOSTNAME "container"
Definition at line 12 of file cli.c.
DEFAULT_MEMORY
#define DEFAULT_MEMORY (512 * 1024 * 1024)
Definition at line 15 of file cli.c.
DEFAULT_ROOTFS
#define DEFAULT_ROOTFS "./rootfs"
Definition at line 13 of file cli.c.
Function Documentation
parse_args()
int parse_args (int argc, char * argv[], ContainerArgs * args)
Parse command-line arguments.
Parses the command-line arguments and fills the ContainerArgs structure with the configuration. If no command is specified, defaults to /bin/sh.
Parameters
argc Number of command-line arguments
argv Array of command-line argument strings
args Pointer to ContainerArgs structure to fill
Returns
EXIT_SUCCESS on success, EXIT_FAILURE on failure
Definition at line 37 of file cli.c.
References DEFAULT_CPUS, DEFAULT_HOSTNAME, DEFAULT_MEMORY, DEFAULT_ROOTFS, ContainerArgs::hostname, ContainerArgs::max_cpus, ContainerArgs::max_memory, print_usage(), ContainerArgs::process, and ContainerArgs::rootfs.
Referenced by main().
print_usage()
static void print_usage (const char * program_name) static
Definition at line 17 of file cli.c.
References DEFAULT_CPUS, DEFAULT_HOSTNAME, DEFAULT_MEMORY, and DEFAULT_ROOTFS.
Referenced by parse_args().